ID ,TargetNo ,name ,School ,Gender ,Rank ,P_128_Rank ,P_64_Rank ,P_32_Rank ,P_16_Rank ,P_8_Rank ,P_4_Rank ,P_half_Rank ,P_Cu_Rank ,P_final_Rank ,G_128_Rank ,G_64_Rank ,G_32_Rank ,G_16_Rank ,G_8_Rank ,G_4_Rank ,G_half_Rank ,G_Cu_Rank ,G_final_Rank ,M_128_Rank ,M_64_Rank ,M_32_Rank ,M_16_Rank ,M_8_Rank ,M_4_Rank ,M_half_Rank ,M_Cu_Rank ,M_final_Rank ,
------------------------------------------
1010,36乙,黄自祥,上海理工大学,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1011,37乙,陆旌尧,上海理工大学,男,None,None,None,33B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1012,38乙,卢永禄,上海理工大学,男,None,None,None,49B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1020,16甲,唐若姝,上海理工大学,女,None,None,None,18A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1021,17甲,王婷,上海理工大学,女,None,None,None,9B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1022,18甲,黄倩仪,上海理工大学,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1110,36丁,陈晟,上海工程技术大学,男,None,None,None,40A,36B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1111,37丁,朱俊宇,上海工程技术大学,男,None,None,None,39B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1112,38丁,葛元晟,上海工程技术大学,男,None,None,None,60B,46B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1120,13丙,顾宇飞,上海工程技术大学,女,None,None,None,26A,13B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1121,14丙,江宜萱,上海工程技术大学,女,None,None,None,30B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1122,15丙,李静怡,上海工程技术大学,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1210,42丁,刘洋,上海健康医学院,男,None,None,None,50B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1211,43丁,徐晨阳,上海健康医学院,男,None,None,None,58B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1212,44丁,冯宝,上海健康医学院,男,None,None,None,48A,40B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1220,1乙,李佩芝,上海健康医学院,女,None,None,None,26B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1221,2乙,叶静,上海健康医学院,女,None,None,None,27B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1222,3乙,梁嘉怡,上海健康医学院,女,None,None,None,20A,10B,5B,3A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1320,7丁,臣贞燕,温州商学院,女,None,None,None,27A,14A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1321,8丁,盛楚惠,温州商学院,女,None,None,None,29A,15A,8A,4B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1322,9丁,秦之雯,温州商学院,女,None,None,None,11A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1410,33丙,志愿,内蒙古医科大学,男,None,None,None,57A,45A,39A,36A,36A,None,26A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1411,34丙,包塔拉,内蒙古医科大学,男,None,None,None,61A,47A,40A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1412,35丙,那日苏,内蒙古医科大学,男,None,None,None,62A,47B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1420,4乙,朝木日力格,内蒙古医科大学,女,None,None,None,6A,3B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1421,5乙,乌日雅,内蒙古医科大学,女,None,None,None,9A,5A,3A,2A,2A,19A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1422,6乙,乌日古木勒,内蒙古医科大学,女,None,None,None,3A,2A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1510,48甲,刘峰源,深圳职业技术学院,男,None,None,None,56B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1511,49甲,吴惠杰,深圳职业技术学院,男,None,None,None,46A,39B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1512,50甲,许思瀚,深圳职业技术学院,男,None,None,None,34A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1520,13丁,冯煜哲,深圳职业技术学院,女,None,None,None,16B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1521,14丁,赖静璇,深圳职业技术学院,女,None,None,None,23A,12A,6B,3B,3A,19B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1522,15丁,朱可儿,深圳职业技术学院,女,None,None,None,10A,5B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1610,45甲,金宗乐,泰山职业技术学院,男,None,None,None,33A,33A,33A,33A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1611,46甲,和晓,泰山职业技术学院,男,None,None,None,47A,40A,36B,34B,34A,27A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1612,47甲,彭子阳,泰山职业技术学院,男,None,None,None,35B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1620,19丁,赵迪,泰山职业技术学院,女,None,None,None,18B,9B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1710,39丙,张琳轩,西北大学,男,None,None,None,59B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1711,40丙,吴德千,西北大学,男,None,None,None,42A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1712,41丙,葛一豪,西北大学,男,None,None,None,42B,37B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1720,4丁,张银晓,西北大学,女,None,None,None,19A,10A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1721,5丁,王慧,西北大学,女,None,None,None,19B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1722,6丁,鲁萌萌,西北大学,女,None,None,None,10B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1810,45丙,吴英杰,东华大学,男,None,None,None,51B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1811,46丙,蔡天培,东华大学,男,None,None,None,52A,42B,37B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1812,47丙,甘振宇,东华大学,男,None,None,None,52B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1820,4丙,施朝禾,东华大学,女,None,None,None,5A,3A,2A,1B,1A,None,17A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1821,5丙,何海婷,东华大学,女,None,None,None,6B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1822,6丙,王雅宁,东华大学,女,None,None,None,2B,1B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1910,48丙,黄文丰,广东工业大学,男,None,None,None,46B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1911,49丙,李军,广东工业大学,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2010,51甲,刘翰扬,西安交通大学,男,None,None,None,41B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2020,10丙,李晓萌,西安交通大学,女,None,None,None,4A,2B,1B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2021,11丙,李永婧,西安交通大学,女,None,None,None,12B,6B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2022,12丙,吕方为,西安交通大学,女,None,None,None,11B,6A,3B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2110,36丙,兴安,内蒙古大学,男,None,None,None,41A,37A,35A,34A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2111,37丙,乌昵,内蒙古大学,男,None,None,None,64A,48B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2112,38丙,阿那尔,内蒙古大学,男,None,None,None,62B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2120,4甲,李娉,内蒙古大学,女,None,None,None,25A,13A,7A,4A,4A,None,18A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2121,5甲,月亮,内蒙古大学,女,None,None,None,21A,11A,6A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2122,6甲,木力日,内蒙古大学,女,None,None,None,31B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2210,36甲,萧百役,暨南大学,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2211,37甲,周智翔,暨南大学,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2212,38甲,陈彦宁,暨南大学,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2220,7乙,卢咏琴,暨南大学,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2221,8乙,谢典庭,暨南大学,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2222,9乙,聂宇芳,暨南大学,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2310,42乙,孙布?,内蒙古科技大学,男,None,None,None,38B,35B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2311,43乙,元丹,内蒙古科技大学,男,None,None,None,45A,39A,36A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2312,44乙,陈国安,内蒙古科技大学,男,None,None,None,37B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2320,7丙,参吉日玛,内蒙古科技大学,女,None,None,None,17B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2321,8丙,柴拉干,内蒙古科技大学,女,None,None,None,25B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2322,9丙,赛俊,内蒙古科技大学,女,None,None,None,20B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2410,42丙,高鑫,西北政法大学,男,None,None,None,35A,34A,33B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2411,43丙,李浩然,西北政法大学,男,None,None,None,43A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2412,44丙,闫佳乐,西北政法大学,男,None,None,None,60A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2420,16丙,赵梦瑶,西北政法大学,女,None,None,None,7A,4A,2B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2421,17丙,房子惠,西北政法大学,女,None,None,None,17A,9A,5A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2422,18丙,车金蓉,西北政法大学,女,None,None,None,22A,11B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2510,33丁,戴幸至,浙江大学,男,None,None,None,45B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2511,34丁,李俊峰,浙江大学,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2512,35丁,徐正阳,浙江大学,男,None,None,None,48B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2520,10丁,包晗潇,浙江大学,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2521,11丁,胡璇,浙江大学,女,None,None,None,32B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2522,12丁,郑金鹏,浙江大学,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2610,45乙,杨曦泽,中国美术学院,男,None,None,None,54A,43B,38A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2611,46乙,谢寅生,中国美术学院,男,None,None,None,47B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2612,47乙,戈凌峰,中国美术学院,男,None,None,None,64B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2620,13甲,刘诗靖,中国美术学院,女,None,None,None,13A,7A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2621,14甲,王方,中国美术学院,女,None,None,None,32A,16B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2622,15甲,徐百卉,中国美术学院,女,None,None,None,15B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2710,42甲,林湃力,复旦大学,男,None,None,None,55B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2711,43甲,王琛,复旦大学,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2712,44甲,杨科洵,复旦大学,男,None,None,None,34B,33B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2720,7甲,俞施熠,复旦大学,女,None,None,None,29B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2721,8甲,郭小小,复旦大学,女,None,None,None,7B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2722,9甲,王瑞琳,复旦大学,女,None,None,None,14A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2810,51乙,徐海川,南京科技职业学院,男,None,None,None,40B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2910,51丁,冯欣玮,天津理工大学,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2920,19甲,杨曼榕,天津理工大学,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3010,48丁,王柯峄,南开大学,男,None,None,None,63B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3012,50丙,赵耀,南开大学,男,None,None,None,38A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3020,19丙,于扬,南开大学,女,None,None,None,8B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3110,45丁,陈狄松,华东政法大学,男,None,None,None,50A,41B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3111,46丁,吴浩龙,华东政法大学,男,None,None,None,44A,38B,35B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3112,47丁,易大为,华东政法大学,男,None,None,None,63A,48A,40B,36B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3120,1丁,黄锦婷,华东政法大学,女,None,None,None,31A,16A,8B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3121,2丁,陈奕菲,华东政法大学,女,None,None,None,22B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3122,3丁,倪韵雯,华东政法大学,女,None,None,None,28A,14B,7B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3210,33乙,周正,上海对外经贸大学,男,None,None,None,49A,41A,37A,35A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3211,34乙,郑智彬,上海对外经贸大学,男,None,None,None,39A,36A,34B,33B,33A,None,25A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3212,35乙,潘茂鹏,上海对外经贸大学,男,None,None,None,51A,42A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3220,13乙,李瑶瑶,上海对外经贸大学,女,None,None,None,1A,1A,1A,1A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3221,14乙,王璐,上海对外经贸大学,女,None,None,None,24A,12B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3222,15乙,陈计羽,上海对外经贸大学,女,None,None,None,12A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3310,39甲,车航波,上海杉达学院,男,None,None,None,57B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3311,40甲,姚鸣捷,上海杉达学院,男,None,None,None,61B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3312,41甲,甘翊文,上海杉达学院,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3320,10乙,温欣欣,上海杉达学院,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3321,11乙,龚佳雯,上海杉达学院,女,None,None,None,1B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3322,12乙,杨萌萌,上海杉达学院,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3420,16丁,杨燕,云南农业大学,女,None,None,None,24B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3421,17丁,童罗澜,云南农业大学,女,None,None,None,3B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3510,39丁,姜子丰,河北司法警官职业学院,男,None,None,None,58A,45B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3511,40丁,马恩泽,河北司法警官职业学院,男,None,None,None,59A,46A,39B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3512,41丁,任荣浪,河北司法警官职业学院,男,None,None,None,53A,43A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3520,10甲,李斌,河北司法警官职业学院,女,None,None,None,30A,15B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3521,11甲,刘美,河北司法警官职业学院,女,None,None,None,2A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3522,12甲,尹铭,河北司法警官职业学院,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3610,33甲,王一鸣,江苏建筑职业技术学院,男,None,None,None,36A,34B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3611,34甲,吴臣,江苏建筑职业技术学院,男,None,None,None,54B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3612,35甲,王振乾,江苏建筑职业技术学院,男,None,None,None,44B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3620,1丙,王珂,江苏建筑职业技术学院,女,None,None,None,4B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3621,2丙,祁雅婷,江苏建筑职业技术学院,女,None,None,None,16A,8B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3622,3丙,吴楠囡,江苏建筑职业技术学院,女,None,None,None,28B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3710,48乙,郑垚,上海政法学院,男,None,None,None,36B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3711,49乙,赵兵兵,上海政法学院,男,None,None,None,43B,38A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3712,50乙,黄鹏飞,上海政法学院,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3720,16乙,黄杜远,上海政法学院,女,None,None,None,23B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3721,17乙,胡静怡,上海政法学院,女,None,None,None,8A,4B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3722,18乙,崔瑞卿,上海政法学院,女,None,None,None,5B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3810,51丙,邱华辰,清华大学,男,None,None,None,53B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3820,19乙,陈汉瑜,清华大学,女,None,None,None,13B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3910,39乙,孟根达来,内蒙古农业大学,男,None,None,None,56A,44B,38B,35B,35A,27B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3911,40乙,白音乌力吉,内蒙古农业大学,男,None,None,None,55A,44A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3912,41乙,沈雪峰,内蒙古农业大学,男,None,None,None,37A,35A,34A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3920,1甲,青格乐,内蒙古农业大学,女,None,None,None,15A,8A,4B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3921,2甲,巴拉吉德玛,内蒙古农业大学,女,None,None,None,14B,7B,4A,2B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3922,3甲,纳荷芽,内蒙古农业大学,女,None,None,None,21B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
b551ee5dc0e3549b7e07e76fc42629a3