ID ,TargetNo ,name ,School ,Gender ,Rank ,P_128_Rank ,P_64_Rank ,P_32_Rank ,P_16_Rank ,P_8_Rank ,P_4_Rank ,P_half_Rank ,P_Cu_Rank ,P_final_Rank ,G_128_Rank ,G_64_Rank ,G_32_Rank ,G_16_Rank ,G_8_Rank ,G_4_Rank ,G_half_Rank ,G_Cu_Rank ,G_final_Rank ,M_128_Rank ,M_64_Rank ,M_32_Rank ,M_16_Rank ,M_8_Rank ,M_4_Rank ,M_half_Rank ,M_Cu_Rank ,M_final_Rank ,
------------------------------------------
1010,9甲,陆嘉诚,上海视觉艺术学院,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1011,10甲,纪冠行,上海视觉艺术学院,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1012,11甲,张蔡寒冰,上海视觉艺术学院,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1013,12甲,吕培欣,上海视觉艺术学院,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1020,6己,程子铭,上海视觉艺术学院,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1021,7己,李若姗,上海视觉艺术学院,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1110,15己,杨林峻,上海政法学院,男,None,None,None,None,14B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1111,16己,董维重,上海政法学院,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1112,17乙,李嘉伟,上海政法学院,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1120,1甲,胡静怡,上海政法学院,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1121,2甲,黄杜远,上海政法学院,女,None,None,None,None,15B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1122,3甲,李诺,上海政法学院,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1123,4甲,崔瑞卿,上海政法学院,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1213,17丁,李海浦,上海工商职业技术学院,男,None,None,None,None,14A,15B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1310,13戊,车航波,上海杉达学院,男,None,None,None,None,6B,11B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1311,14戊,王知灏,上海杉达学院,男,None,None,None,None,9B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1312,15戊,姚鸣捷,上海杉达学院,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1313,16戊,韩杨,上海杉达学院,男,None,None,None,None,5B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1320,1己,赖宣如,上海杉达学院,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1321,2己,龚佳雯,上海杉达学院,女,None,None,None,None,10B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1322,3己,张语恬,上海杉达学院,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1323,4己,章雯,上海杉达学院,女,None,None,None,None,2A,1B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1410,9丙,王廷锴,上海大学,男,None,None,None,None,5A,11A,10A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1411,10丙,蒙兆仪,上海大学,男,None,None,None,None,2A,9B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1412,11丙,陶星宇,上海大学,男,None,None,None,None,8A,12B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1413,12丙,罗航凯,上海大学,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1420,5丙,胡雨川,上海大学,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1421,6丙,黄丹若,上海大学,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1422,7丙,丁钰航,上海大学,女,None,None,None,None,16B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1423,8丙,刘璇,上海大学,女,None,None,None,None,11B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1510,9丁,严文豪,华东政法大学,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1511,10丁,回珉,华东政法大学,男,None,None,None,None,4A,10B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1512,11丁,冯康,华东政法大学,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1513,12丁,张源,华东政法大学,男,None,None,None,None,2B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1520,5丁,陈奕菲,华东政法大学,女,None,None,None,None,5A,3A,2A,2A,3A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1521,6丁,黎澄澄,华东政法大学,女,None,None,None,None,14B,7B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1522,7丁,焦雨晴,华东政法大学,女,None,None,None,None,3A,2A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1610,13己,王栋,东华大学,男,None,None,None,None,12B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1611,14己,何达,东华大学,男,None,None,None,None,16A,16B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1612,17甲,蔡天培,东华大学,男,None,None,None,None,10B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1613,17丙,吴英杰,东华大学,男,None,None,None,None,7B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1620,5乙,施朝禾,东华大学,女,None,None,None,None,1A,1A,1A,1A,None,1A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1621,6乙,曾羽佳,东华大学,女,None,None,None,None,4A,2B,1B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1622,7乙,王哲,东华大学,女,None,None,None,None,1B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1623,8乙,王爱华,东华大学,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1710,13丁,李磊,上海工程技术大学,男,None,None,None,None,4B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1711,14丁,陈晟,上海工程技术大学,男,None,None,None,None,16B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1712,15丁,朱俊宇,上海工程技术大学,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1713,16丁,葛元晟,上海工程技术大学,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1720,5戊,李静怡,上海工程技术大学,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1721,6戊,顾宇飞,上海工程技术大学,女,None,None,None,None,8B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1723,8丁,江宜萱,上海工程技术大学,女,None,None,None,None,13B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1810,9己,冯宝,上海健康医学院,男,None,None,None,None,9A,13A,11A,11A,11B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1811,10己,刘洋,上海健康医学院,男,None,None,None,None,12A,14B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1812,11己,徐晨阳,上海健康医学院,男,None,None,None,None,3A,10A,9B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1813,12己,肖阳,上海健康医学院,男,None,None,None,None,8B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1820,1丁,李佩芝,上海健康医学院,女,None,None,None,None,12A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1821,2丁,梁嘉怡,上海健康医学院,女,None,None,None,None,15A,8A,4B,4A,None,2A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1822,3丁,叶静,上海健康医学院,女,None,None,None,None,16A,8B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1823,4丁,丁佳雯,上海健康医学院,女,None,None,None,None,4B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1910,13甲,周正,上海对外经贸大学,男,None,None,None,None,10A,13B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1911,14甲,郑智彬,上海对外经贸大学,男,None,None,None,None,13A,15A,12A,12A,None,10A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1912,15甲,潘茂鹏,上海对外经贸大学,男,None,None,None,None,7A,12A,10B,10A,11A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1913,16甲,吴德彰,上海对外经贸大学,男,None,None,None,None,11A,14A,11B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1920,1乙,李瑶瑶,上海对外经贸大学,女,None,None,None,None,9A,5A,3A,3A,3B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1921,2乙,陈计羽,上海对外经贸大学,女,None,None,None,None,7A,4A,2B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1922,3乙,王屾妍,上海对外经贸大学,女,None,None,None,None,6B,3B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1923,4乙,王欣,上海对外经贸大学,女,None,None,None,None,13A,7A,4A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2010,9戊,王琛,复旦大学,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2011,10戊,林湃力,复旦大学,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2012,11戊,李禹杭,复旦大学,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2013,12戊,田森,复旦大学,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2020,1丙,赵潇涵,复旦大学,女,None,None,None,None,12B,6B,3B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2021,2丙,朱彧璇,复旦大学,女,None,None,None,None,3B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2022,3丙,王瑞琳,复旦大学,女,None,None,None,None,2B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2023,4丙,李黛丽,复旦大学,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2110,13丙,吴康,华东师范大学,男,None,None,None,None,3B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2111,14丙,徐霆晖,华东师范大学,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2112,15丙,杨经纬,华东师范大学,男,None,None,None,None,1B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2113,16丙,夏文涛,华东师范大学,男,None,None,None,None,13B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2120,1戊,珠拉,华东师范大学,女,None,None,None,None,8A,4B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2121,2戊,刁文萱,华东师范大学,女,None,None,None,None,7B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2122,3戊,单雪洁,华东师范大学,女,None,None,None,None,6A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2123,4戊,冯靓玥,华东师范大学,女,None,None,None,None,5B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2210,13乙,童良晶,上海体育学院,男,None,None,None,None,1A,9A,9A,9A,None,9A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2211,14乙,代梧佑,上海体育学院,男,None,None,None,None,15A,16A,12B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2212,15乙,刘潇阳,上海体育学院,男,None,None,None,None,11B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2213,16乙,张朝琨,上海体育学院,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2220,5甲,刘金燕,上海体育学院,女,None,None,None,None,11A,6A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2221,6甲,居涵冰,上海体育学院,女,None,None,None,None,14A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2222,7甲,申梦悦,上海体育学院,女,None,None,None,None,9B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2223,8甲,李佳丛,上海体育学院,女,None,None,None,None,10A,5B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2310,9乙,孙阳严,上海理工大学,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2311,10乙,卢永禄,上海理工大学,男,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2312,11乙,沈五一,上海理工大学,男,None,None,None,None,15B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2313,12乙,黄自祥,上海理工大学,男,None,None,None,None,6A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2322,7戊,杜意意,上海理工大学,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2323,5己,黄倩仪,上海理工大学,女,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
65ba37285d988daaaf3eee8fe8a68fb2